# Checkpoint Three: Cleaning Data

Now you are ready to clean your data. Before starting coding, provide the link to your dataset below.

My dataset:

Import the necessary libraries and create your dataframe(s).

In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

bgg_data = r'C:\Users\willm\Desktop\launchcode\cleaning-data-checkpoint\bggdata2023\bgg_GameItem.csv'
bgg_theme = r'C:\Users\willm\Desktop\launchcode\cleaning-data-checkpoint\bggdata2023\bgg_Category.csv'

def reimport_csv(filepath):
    return pd.read_csv(filepath)

df = reimport_csv(bgg_data)
df_theme = reimport_csv(bgg_theme)

df = df.sort_values('rank', ascending=True)

theme_map = df_theme.set_index('bgg_id')['name'].to_dict()

def map_id_to_theme(theme_ids):
    if pd.isna(theme_ids):
        return theme_ids
    ids = theme_ids.split(',')
    names = [theme_map.get(int(cat_id.strip()), 'Unknown') for cat_id in ids]
    return names


df['category'] = df['category'].apply(map_id_to_theme)

In [61]:
df_filtered = df[df['rank'].notna()]

df_filtered_small = df[df['rank'] <= 2000]

In [62]:
df_exploded = df.explode('category')
df_grouped = df_exploded.groupby(['year','category']).size().reset_index(name='count')

df_filtered_exploded = df_filtered.explode('category')
df_filtered_grouped = df_filtered_exploded.groupby(['year','category']).size().reset_index(name='count')

df_fs_exploded = df_filtered_small.explode('category')
df_fs_grouped = df_fs_exploded.groupby(['year','category']).size().reset_index(name='count')

## Missing Data

Test your dataset for missing data and handle it as needed. Make notes in the form of code comments as to your thought process.

## Irregular Data

Detect outliers in your dataset and handle them as needed. Use code comments to make notes about your thought process.

## Unnecessary Data

Look for the different types of unnecessary data in your dataset and address it as needed. Make sure to use code comments to illustrate your thought process.

In [63]:
pd.set_option('display.max_columns', None)
display(df_exploded.describe())

,bgg_id,year,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,min_age_rec,min_time,max_time,cooperative,compilation,rank,num_votes,avg_rating,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
count,276375.000000,255569.000000,272687.000000,264077.000000,272687.000000,264077.000000,272687.000000,264077.000000,227451.000000,3602.000000,228146.000000,2.281460e+05,19648.0,2598.0,64687.000000,213032.000000,213032.000000,171640.000000,65978.000000,124194.000000,2689.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,159945.858623,2004.076621,2.014075,7.006078,2.021314,6.978124,2.065108,6.945819,9.685532,10.185789,53.279913,1.069644e+03,1.0,1.0,11928.702011,328.399611,6.252667,1.528551,5.697382,1.948023,2.322532,NaN,NaN,NaN,NaN,NaN,NaN
std,124192.732702,59.782333,0.863667,45.452081,0.871836,45.434487,0.922191,45.437371,5.414258,2.880076,661.861463,1.786839e+05,0.0,0.0,7147.113863,2469.747398,1.597821,0.621027,0.385677,0.844502,1.222660,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,-3500.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.045455,1.000000,1.000000e+00,1.0,1.0,1.000000,1.000000,1.000000,0.000500,3.624890,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,33851.500000,2001.000000,2.000000,4.000000,2.000000,4.000000,2.000000,4.000000,8.000000,8.142857,15.000000,2.000000e+01,1.0,1.0,5672.500000,2.000000,5.333330,1.200000,5.511000,1.066700,1.036232,NaN,NaN,NaN,NaN,NaN,NaN
50%,146356.000000,2011.000000,2.000000,4.000000,2.000000,4.000000,2.000000,4.000000,10.000000,10.208333,30.000000,4.000000e+01,1.0,1.0,11815.000000,8.000000,6.303865,1.480120,5.544990,2.000000,2.110465,NaN,NaN,NaN,NaN,NaN,NaN
75%,274443.500000,2018.000000,2.000000,6.000000,2.000000,6.000000,2.000000,6.000000,12.000000,12.071429,60.000000,9.000000e+01,1.0,1.0,18068.000000,48.000000,7.206302,1.790512,5.686120,2.500000,3.400000,NaN,NaN,NaN,NaN,NaN,NaN
max,392146.000000,2026.000000,50.000000,11299.000000,50.000000,11299.000000,50.000000,11299.000000,2017.000000,20.541667,157680.000000,6.307200e+07,1.0,1.0,24481.000000,119186.000000,10.000000,4.500000,8.423300,5.000000,4.983333,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
df.drop([
    'min_players',
    'max_players',
    'min_players_rec',
    'max_players_rec',
    'min_players_best',
    'max_players_best',
    'bga_id', 
    'dbpedia_id', 
    'luding_id', 
    'spielen_id', 
    'wikidata_id', 
    'wikipedia_id'], axis=1, inplace=True)

display(df)

,bgg_id,name,year,game_type,designer,artist,publisher,min_age,min_age_rec,min_time,max_time,category,mechanic,cooperative,compilation,compilation_of,family,implementation,integration,rank,num_votes,avg_rating,stddev_rating,bayes_rating,complexity,language_dependency
76224,224517,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",14.0,13.825758,60.0,120.0,"[Economic, Industry / Manufacturing, Post-Napo...","2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,NaN,NaN,"17519,65191,14759,8374,22135,77349,70948,26397...",28720,NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955,1.023810
62813,161936,Pandemic Legacy: Season 1,2015.0,"5496,5497","442,378",14057,"538,15889,2366,5657,8820,1391,15983,8291,5812,...",13.0,11.760000,60.0,60.0,"[Environmental, Medical]","2001,2023,2040,2824,2078,2822,2004,3100,2008,2015",1.0,NaN,NaN,"64952,65191,3430,24281,25404,61854,72224,78680...",30549,NaN,2.0,50631.0,8.53562,1.60680,8.38972,2.8318,4.085938
66014,174430,Gloomhaven,2017.0,"5496,5497",69802,"77084,78961,84269","27425,4304,46179,3475,22380,15605,40478,8820,1...",14.0,13.602113,60.0,120.0,"[Adventure, Exploration, Fantasy, Fighting, Mi...","2689,2839,2018,2857,2893,2023,2854,3004,2676,2...",1.0,NaN,NaN,"59218,25158,65191,66335,68438,7005,5615,8374,7...",NaN,"295770,291457",3.0,58418.0,8.62311,1.75165,8.38865,3.8959,4.166667
102831,342942,Ark Nova,2021.0,5497,138517,"138547,11462,12484,11797","22380,30958,21608,10768,12540,8820,42325,17179...",14.0,12.442623,90.0,150.0,"[Animals, Economic, Environmental]","2875,2040,2026,2902,2914,2041,2004,2819,3100,2...",NaN,NaN,NaN,"67874,70360,73596,76649,5666,68335,66167,76846",NaN,NaN,4.0,31052.0,8.53405,1.38518,8.30236,3.7249,3.712121
78094,233078,Twilight Imperium: Fourth Edition,2017.0,"5496,5497","96049,6651,21",11988,"17,23043,3475,157,15889,2973,4617,15605,18852,...",14.0,14.135135,240.0,480.0,"[Civilization, Economic, Exploration, Negotiat...","2838,2080,2021,2072,2843,2676,2026,2914,2886,2...",NaN,NaN,NaN,"67874,64949,25158,29,12210,78680",12493,NaN,5.0,20922.0,8.61973,1.61439,8.24243,4.3080,4.093750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113899,391565,Champions!,2023.0,NaN,"62310,62311,6736",NaN,"4384,1391",10.0,NaN,30.0,45.0,[Party Game],2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113900,391715,Leitin að stjörnunni,2022.0,NaN,"154290,123339,154289",NaN,54258,5.0,NaN,30.0,30.0,"[Children's Game, Movies / TV / Radio theme, P...","2073,2038,2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113901,391720,The String Railway Collection,2024.0,NaN,39436,113637,44392,10.0,NaN,20.0,45.0,"[Territory Building, Trains]","2011,2081,2007",NaN,1.0,"76674,100473",11331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113902,391834,SpellBook,2023.0,NaN,8347,45292,25842,12.0,NaN,45.0,45.0,[Fantasy],"2040,2004,2819",NaN,NaN,NaN,22184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113903,392146,Nightmares of Sushi,2023.0,NaN,81537,81537,52244,8.0,NaN,15.0,30.0,"[Card Game, Deduction, Humor]","2857,3002,2875,2040,2047",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df_filtered = df[df['rank'].notna()]

df_filtered_small = df[df['rank'] <= 2000]

df_exploded = df.explode('category')
df_grouped = df_exploded.groupby(['year','category']).size().reset_index(name='count')

df_filtered_exploded = df_filtered.explode('category')
df_filtered_grouped = df_filtered_exploded.groupby(['year','category']).size().reset_index(name='count')

df_fs_exploded = df_filtered_small.explode('category')
df_fs_grouped = df_fs_exploded.groupby(['year','category']).size().reset_index(name='count')

In [69]:
df_theme_exploded = df_exploded[
    (df_exploded['category'] != 'Card Game') |
    (df_exploded['category'] != 'Bluffing') |
    (df_exploded['category'] != 'Print & Play') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Action / Dexterity')]
df_theme_filtered_exploded = df_filtered_exploded[
    (df_filtered_exploded['category'] != 'Card Game') |
    (df_filtered_exploded['category'] != 'Bluffing') |
    (df_filtered_exploded['category'] != 'Print & Play') |
    (df_filtered_exploded['category'] != 'Real-time') |
    (df_filtered_exploded['category'] != 'Action / Dexterity')]
df_theme_fs_exploded = df_fs_exploded[
    (df_fs_exploded['category'] != 'Card Game') |
    (df_fs_exploded['category'] != 'Bluffing') |
    (df_fs_exploded['category'] != 'Print & Play') |
    (df_fs_exploded['category'] != 'Real-time') |
    (df_fs_exploded['category'] != 'Action / Dexterity')]

## Inconsistent Data

Check for inconsistent data and address any that arises. As always, use code comments to illustrate your thought process.

## Summarize Your Results

Make note of your answers to the following questions.

1. Did you find all four types of dirty data in your dataset?
2. Did the process of cleaning your data give you new insights into your dataset?
3. Is there anything you would like to make note of when it comes to manipulating the data and making visualizations?